"""Train a small PINN residual ensemble from a dataset made by xlog_dataset.py.

Example:
  python learning/training/train_pinn.py learning/datasets/auv_v1.npz \
      --output learning/export/run-001 --epochs 200 --ensemble 5
"""
from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

from pinn_residual import AXIS_NAMES, ModelConfig, axis_mask, dynamics_input


def choose_split(source_run: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Hold out whole runs; use a temporal holdout only when one run is available."""
    unique_runs = np.unique(source_run)
    if len(unique_runs) >= 2:
        validation_run = unique_runs[-1]
        validation = np.flatnonzero(source_run == validation_run)
        training = np.flatnonzero(source_run != validation_run)
    else:
        split = max(1, int(len(source_run) * 0.8))
        training = np.arange(split)
        validation = np.arange(split, len(source_run))
    if len(training) == 0 or len(validation) == 0:
        raise ValueError("dataset needs both training and validation transitions")
    return training, validation


def tensors(dataset: np.lib.npyio.NpzFile, indices: np.ndarray, device: torch.device) -> tuple[torch.Tensor, ...]:
    eta = torch.as_tensor(dataset["eta"][indices], dtype=torch.float32, device=device)
    nu = torch.as_tensor(dataset["nu"][indices], dtype=torch.float32, device=device)
    tau = torch.as_tensor(dataset["tau_base"][indices], dtype=torch.float32, device=device)
    next_nu = torch.as_tensor(dataset["next_nu"][indices], dtype=torch.float32, device=device)
    dt = torch.as_tensor(dataset["dt"][indices], dtype=torch.float32, device=device).unsqueeze(-1)
    target_acceleration = (next_nu - nu) / dt.clamp_min(1.0e-4)
    return eta, nu, tau, target_acceleration


def mean_metrics(model: torch.nn.Module, batch: tuple[torch.Tensor, ...], active_axes: torch.Tensor) -> dict[str, float]:
    model.eval()
    with torch.no_grad():
        eta, nu, tau, target = batch
        prediction, _force, _variance = model(eta, nu, tau)
        baseline, _force, _variance = model.prior(nu, tau, torch.zeros_like(tau)), torch.zeros_like(tau), torch.zeros_like(tau)
        mask = active_axes.to(eta.device)
        scale = mask.sum().clamp_min(1.0)
        model_mse = (((prediction - target).square() * mask).sum(dim=-1) / scale).mean()
        baseline_mse = (((baseline - target).square() * mask).sum(dim=-1) / scale).mean()
    return {"model_mse": float(model_mse.cpu()), "baseline_mse": float(baseline_mse.cpu())}


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a HydroX PINN residual ensemble")
    parser.add_argument("dataset", help=".npz generated by xlog_dataset.py")
    parser.add_argument("--output", required=True, help="directory for checkpoints and metrics")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--learning-rate", type=float, default=3.0e-4)
    parser.add_argument("--ensemble", type=int, default=5)
    parser.add_argument("--axes", default="X,M,N", help="comma-separated wrench axes")
    parser.add_argument("--mass-kg", type=float, default=70.0)
    parser.add_argument("--pitch-inertia", type=float, default=26.0)
    parser.add_argument("--yaw-inertia", type=float, default=30.0)
    parser.add_argument("--seed", type=int, default=20260725)
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda, or cuda:0")
    args = parser.parse_args()

    dataset = np.load(args.dataset, allow_pickle=False)
    training_indices, validation_indices = choose_split(dataset["source_run"])
    requested_axes = tuple(value.strip().upper() for value in args.axes.split(",") if value.strip())
    if not requested_axes:
        raise ValueError("--axes must select at least one axis")
    active_axes = axis_mask(requested_axes)
    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)
    config = ModelConfig(axes=requested_axes, mass_kg=args.mass_kg,
                         pitch_inertia_kg_m2=args.pitch_inertia, yaw_inertia_kg_m2=args.yaw_inertia)

    full_eta = torch.as_tensor(dataset["eta"][training_indices], dtype=torch.float32)
    full_nu = torch.as_tensor(dataset["nu"][training_indices], dtype=torch.float32)
    full_tau = torch.as_tensor(dataset["tau_base"][training_indices], dtype=torch.float32)
    raw_features = dynamics_input(full_eta, full_nu, full_tau)
    input_mean = raw_features.mean(dim=0)
    input_std = raw_features.std(dim=0).clamp_min(1.0e-4)
    train_batch = tensors(dataset, training_indices, device)
    validation_batch = tensors(dataset, validation_indices, device)
    train_loader = DataLoader(TensorDataset(*train_batch), batch_size=args.batch_size, shuffle=True)

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    all_metrics: list[dict[str, float]] = []
    for member in range(args.ensemble):
        seed = args.seed + member
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        model = config.build(input_mean, input_std).to(device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=1.0e-5)
        for epoch in range(1, args.epochs + 1):
            model.train()
            for eta, nu, tau, target in train_loader:
                optimizer.zero_grad(set_to_none=True)
                loss = model.loss(eta, nu, tau, target)["total"]
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            if epoch == 1 or epoch % max(1, args.epochs // 10) == 0:
                metrics = mean_metrics(model, validation_batch, active_axes)
                print(f"member={member} epoch={epoch} validation_mse={metrics['model_mse']:.6g} "
                      f"baseline_mse={metrics['baseline_mse']:.6g}")
        metrics = mean_metrics(model, validation_batch, active_axes)
        metrics["member"] = member
        metrics["seed"] = seed
        all_metrics.append(metrics)
        torch.save({"format": "hydrox.pinn-residual/v1", "model_state": model.state_dict(),
                    "input_mean": input_mean, "input_std": input_std,
                    "config": {"axes": config.axes, "mass_kg": config.mass_kg,
                               "pitch_inertia_kg_m2": config.pitch_inertia_kg_m2,
                               "yaw_inertia_kg_m2": config.yaw_inertia_kg_m2,
                               "residual_force_limits": config.residual_force_limits,
                               "width": config.width, "depth": config.depth},
                    "validation": metrics}, output / f"pinn_member_{member:02d}.pt")

    report = {"format": "hydrox.pinn-ensemble-report/v1", "dataset": str(Path(args.dataset)),
              "training_samples": int(len(training_indices)), "validation_samples": int(len(validation_indices)),
              "active_axes": list(requested_axes), "axis_names": list(AXIS_NAMES),
              "members": all_metrics}
    (output / "pinn_metrics.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
