/**
 * uart_transport.cpp — UART transport layer (for STM32/Pixhawk hardware)
 *
 * Implemented on STM32 via HAL_UART_Receive_DMA / HAL_UART_Transmit.
 * This file is a stub implementation and is not linked when compiling the SITL target.
 */
#include "transport.h"

#ifndef HYDROX_TRANSPORT_TCP

#include <cstring>
// STM32 HAL header files (paths provided by CMakeLists during cross-compilation)
#ifdef STM32H7xx
#include "stm32h7xx_hal.h"
extern UART_HandleTypeDef huart2; // Generated by CubeMX
static UART_HandleTypeDef *_huart = &huart2;
#endif

namespace hydrox
{

    class UartTransport : public Transport
    {
    public:
        UartTransport() = default;
        ~UartTransport() override { disconnect(); }

        bool connect() override
        {
#ifdef STM32H7xx
            // HAL has already been initialized by MX_USART2_UART_Init(), return true directly
            _connected = true;
            return true;
#else
            return false;
#endif
        }

        void disconnect() override { _connected = false; }

        int read(uint8_t *buf, size_t len) override
        {
#ifdef STM32H7xx
            HAL_StatusTypeDef s = HAL_UART_Receive(_huart, buf, len, 0);
            if (s == HAL_OK)
                return static_cast<int>(len);
            if (s == HAL_TIMEOUT)
                return 0;
            _connected = false;
            return -1;
#else
            (void)buf;
            (void)len;
            return -1;
#endif
        }

        bool write(const uint8_t *buf, size_t len) override
        {
#ifdef STM32H7xx
            return HAL_UART_Transmit(_huart, const_cast<uint8_t *>(buf), len, 100) == HAL_OK;
#else
            (void)buf;
            (void)len;
            return false;
#endif
        }

        bool is_connected() const override { return _connected; }

    private:
        bool _connected = false;
    };

} // namespace hydrox
#endif // !HYDROX_TRANSPORT_TCP
