#!/usr/bin/env python3
"""Generate the immutable FMUv6C multi-vehicle profile registry."""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
import sys


HYDROX_ROOT = Path(__file__).resolve().parents[1]
HEADER = HYDROX_ROOT / "include/hydrox/runtime/generated_fmuv6c_profiles.h"
MANIFEST = HYDROX_ROOT / "profiles/fmuv6c-profile-registry.json"


@dataclass(frozen=True)
class ProfileSpec:
    profile_id: str
    vehicle_type: str
    mav_type: int
    source: Path
    source_label: str


SPECS = (
    ProfileSpec("generic-auv-fin", "generic-auv-fin", 12,
        HYDROX_ROOT / "profiles/generic-auv-fin/vehicle-bundle.json",
        "profiles/generic-auv-fin/vehicle-bundle.json"),
    ProfileSpec("EcaA9", "EcaA9", 12,
        HYDROX_ROOT / "profiles/eca-a9/vehicle-bundle.json",
        "profiles/eca-a9/vehicle-bundle.json"),
    ProfileSpec("LAUV", "LAUV", 12,
        HYDROX_ROOT / "profiles/lauv/vehicle-bundle.json",
        "profiles/lauv/vehicle-bundle.json"),
    ProfileSpec("DesistekSaga", "DesistekSaga", 12,
        HYDROX_ROOT / "profiles/desistek-saga/vehicle-bundle.json",
        "profiles/desistek-saga/vehicle-bundle.json"),
    ProfileSpec("RexROV2", "RexROV2", 12,
        HYDROX_ROOT / "profiles/rexrov2/vehicle-bundle.json",
        "profiles/rexrov2/vehicle-bundle.json"),
    ProfileSpec("VRX_WAMV", "VRX_WAMV", 11,
        HYDROX_ROOT / "profiles/wamv/vehicle-bundle.json",
        "profiles/wamv/vehicle-bundle.json"),
    ProfileSpec("X500", "X500", 2,
        HYDROX_ROOT / "profiles/x500/vehicle-bundle.json",
        "profiles/x500/vehicle-bundle.json"),
    ProfileSpec("RCCessna", "RCCessna", 1,
        HYDROX_ROOT / "profiles/rc-cessna/vehicle-bundle.json",
        "profiles/rc-cessna/vehicle-bundle.json"),
    ProfileSpec("StandardVTOL", "StandardVTOL", 19,
        HYDROX_ROOT / "profiles/standard-vtol/vehicle-bundle.json",
        "profiles/standard-vtol/vehicle-bundle.json"),
    ProfileSpec("R1Rover", "R1Rover", 10,
        HYDROX_ROOT / "profiles/r1-rover/vehicle-bundle.json",
        "profiles/r1-rover/vehicle-bundle.json"),
)


def fnv1a64(data: bytes) -> int:
    value = 14695981039346656037
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return value


def cpp_bytes(name: str, data: bytes) -> str:
    lines = [f"inline constexpr char {name}[] ="]
    for offset in range(0, len(data), 24):
        chunk = data[offset : offset + 24]
        lines.append('    "' + "".join(f"\\x{byte:02x}" for byte in chunk) + '"')
    lines.append("    ;")
    return "\n".join(lines)


def generated_documents() -> tuple[str, str]:
    blobs: list[str] = []
    rows: list[str] = []
    manifest_profiles: list[dict[str, object]] = []
    for index, spec in enumerate(SPECS):
        if not spec.source.is_file():
            raise FileNotFoundError(f"profile source is missing: {spec.source}")
        data = spec.source.read_bytes()
        try:
            document = json.loads(data.decode("utf-8"))
            if document.get("schema_version") != "2.0" or document.get("id") != spec.vehicle_type:
                raise ValueError(f"invalid VehicleBundle identity/schema: {spec.source}")
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise ValueError(
                f"invalid UTF-8 JSON profile source {spec.source}: {exc}") from exc
        fingerprint = fnv1a64(data)
        digest = hashlib.sha256(data).hexdigest()
        symbol = f"kFmuv6cProfileJson{index}"
        blobs.append(cpp_bytes(symbol, data))
        rows.append(
            "    GeneratedFmuv6cProfileDocument{"
            f'"{spec.profile_id}", '
            f'"{spec.source_label}", 0x{fingerprint:016X}ULL, '
            f"{spec.mav_type}, {symbol}, "
            f"sizeof({symbol}) - 1}},")
        manifest_profiles.append({
            "profile_id": spec.profile_id,
            "vehicle_type": spec.vehicle_type,
            "mav_type": spec.mav_type,
            "source": spec.source_label,
            "format": "vehicle_bundle",
            "bytes": len(data),
            "fingerprint": f"{fingerprint:016X}",
            "sha256": digest,
        })

    header = """// Generated by tools/generate_fmuv6c_profile_registry.py. DO NOT EDIT.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace hydrox::runtime
{
struct GeneratedFmuv6cProfileDocument
{
    const char *profile_id;
    const char *source_path;
    uint64_t fingerprint;
    uint8_t mav_type;
    const char *json;
    std::size_t json_size;
};

""" + "\n\n".join(blobs) + """

inline constexpr std::array<GeneratedFmuv6cProfileDocument, %d>
    kGeneratedFmuv6cProfiles = {{
%s
}};
} // namespace hydrox::runtime
""" % (len(SPECS), "\n".join(rows))

    manifest = json.dumps({
        "schema_version": 1,
        "generator": "tools/generate_fmuv6c_profile_registry.py",
        "profile_count": len(SPECS),
        "profiles": manifest_profiles,
    }, indent=2) + "\n"
    return header, manifest


def update(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        return True
    if check:
        print(f"out-of-date generated file: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"generated {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    header, manifest = generated_documents()
    ok = update(HEADER, header, args.check)
    ok = update(MANIFEST, manifest, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
